name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    name: Terraform Apply
    env:
      WORKDIR: ${{ vars.WORKDIR }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install "yq"
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Get All Modified Files
      id: changed-files
      uses: tj-actions/changed-files@v35

    - name: Touch All Modified Files
      run: bash scripts/touch.sh
      env:
        FILES: ${{ steps.changed-files.outputs.all_modified_files }}

    - name: Generate Makefile
      run: bash scripts/build.sh
    
    - name: Terraform Apply
      run: make -f tfmake/makefiles/apply/Makefile

    - name: Mermaid Diagram
      run: bash scripts/mermaid.sh
      env:
        CLASS_DEF_DEFAULT: ${{ vars.CLASS_DEF_DEFAULT }}
        CLASS_DEF_VISITED: ${{ vars.CLASS_DEF_VISITED }}

    - name: Terraform Outputs
      run: bash scripts/apply_logs.sh
